#!/usr/bin/env bash

# jq: programa used to manipulate JSON. Here it is used
# to format JSON from API response, getted by CURL.
type jq &> /dev/null

if [[ $? -ne 0 ]]; then
	echo "Critical command/executable not found: jq"
	exit 1
fi


declare -r SCRIPT_PATH=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &> /dev/null && pwd)
declare -r PROTOCOL="$1"
declare -r URL="$2"
declare -r JSON="$3"


if [[ -z $URL ]]; then
	echo -e "URL not specified."
	exit 1;
fi

function check_json(){
	declare is_mandatory=$1

	if [[ $is_mandatory -eq 0 ]]; then
		if [[ -z $JSON ]]; then
			echo "JSON not specified."
			exit 1
		fi

	elif [[ ! -z $JSON ]]; then
		echo "This protocol not require a JSON, it was ignored"
	fi
}


if [[ $PROTOCOL = "get" ]]; then
	check_json 1
	"$SCRIPT_PATH"/get "$URL"

elif [[ $PROTOCOL = "post" ]]; then
	check_json 0
	"$SCRIPT_PATH"/post "$URL" "$JSON"

else
	echo "Invalid or unsupported HTTP protocol: $PROTOCOL"
	exit 1
fi

exit 0
